version: '3'
services:
  app:
    build: .
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/app
    environment:
      - APP_PORT
      - NEXT_PUBLIC_AW_ENDPOINT
      - NEXT_PUBLIC_AW_PROJECT
      - NEXT_PUBLIC_AW_DATABASE
      - NEXT_PUBLIC_TABLE_COLLECTION
      - NEXT_PUBLIC_ORDER_COLLECTION
      - NEXT_PUBLIC_PRODUCT_COLLECTION
